version: '3.8'

services:
  backend:
    container_name: backend_container
    build:
      context: .
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["sh", "./start.sh"]

  postgres_db:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
